# Generated by Django 5.1.4 on 2025-01-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_category_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('perex', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=50)),
                ('link', models.DateField(max_length=400)),
            ],
        ),
    ]
