# Generated by Django 5.1.4 on 2025-02-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_category_options_remove_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='articles', to='content.category'),
        ),
    ]
