# Generated by Django 5.1.4 on 2025-02-06 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_article_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='published',
            new_name='lastUpdate',
        ),
        migrations.RemoveField(
            model_name='article',
            name='perex',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
        migrations.AddField(
            model_name='article',
            name='biom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='dodatkovyText',
            field=models.TextField(default='Neznámé'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='version',
            field=models.TextField(default='Neznámé', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='vyroba',
            field=models.TextField(default='Neznámé', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='zakladniInfo',
            field=models.TextField(default='Neznámé'),
        ),
    ]
