# Generated by Django 5.1.4 on 2025-02-08 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_rename_published_article_lastupdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Biomes',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='biom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.biom'),
        ),
    ]
