# Generated by Django 5.1.4 on 2025-02-08 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_biom_alter_article_biom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='biom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.biom'),
        ),
    ]
