# Generated by Django 5.1.4 on 2025-03-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='vote_sum',
            field=models.IntegerField(default=0),
        ),
    ]
